In [8]:
import pandas as pd
import numpy as np

import altair as alt

In [9]:
df = pd.read_csv("data/train.csv")

In [10]:
df.head()

,Year_Factor,State_Factor,building_class,facility_type,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,...,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,id
0,1,State_1,Commercial,Grocery_store_or_food_market,61242.0,1942.0,11.0,2.4,36,50.5,...,14,0,0,0,1.0,1.0,1.0,NaN,248.682615,0
1,1,State_1,Commercial,Warehouse_Distribution_or_Shipping_center,274000.0,1955.0,45.0,1.8,36,50.5,...,14,0,0,0,1.0,NaN,1.0,12.0,26.500150,1
2,1,State_1,Commercial,Retail_Enclosed_mall,280025.0,1951.0,97.0,1.8,36,50.5,...,14,0,0,0,1.0,NaN,1.0,12.0,24.693619,2
3,1,State_1,Commercial,Education_Other_classroom,55325.0,1980.0,46.0,1.8,36,50.5,...,14,0,0,0,1.0,NaN,1.0,12.0,48.406926,3
4,1,State_1,Commercial,Warehouse_Nonrefrigerated,66000.0,1985.0,100.0,2.4,36,50.5,...,14,0,0,0,1.0,1.0,1.0,NaN,3.899395,4

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75757 entries, 0 to 75756
Data columns (total 64 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year_Factor                75757 non-null  int64
 1   State_Factor               75757 non-null  object
 2   building_class             75757 non-null  object
 3   facility_type              75757 non-null  object
 4   floor_area                 75757 non-null  float64
 5   year_built                 73920 non-null  float64
 6   energy_star_rating         49048 non-null  float64
 7   ELEVATION                  75757 non-null  float64
 8   january_min_temp           75757 non-null  int64
 9   january_avg_temp           75757 non-null  float64
 10  january_max_temp           75757 non-null  int64
 11  february_min_temp          75757 non-null  int64
 12  february_avg_temp          75757 non-null  float64
 13  february_max_temp          75757 non-null  int64
 14  march_min_temp             75757 non-null  int64
 15  march_avg_temp             75757 non-null  float64
 16  march_max_temp             75757 non-null  int64
 17  april_min_temp             75757 non-null  int64
 18  april_avg_temp             75757 non-null  float64
 19  april_max_temp             75757 non-null  int64
 20  may_min_temp               75757 non-null  int64
 21  may_avg_temp               75757 non-null  float64
 22  may_max_temp               75757 non-null  int64
 23  june_min_temp              75757 non-null  int64
 24  june_avg_temp              75757 non-null  float64
 25  june_max_temp              75757 non-null  int64
 26  july_min_temp              75757 non-null  int64
 27  july_avg_temp              75757 non-null  float64
 28  july_max_temp              75757 non-null  int64
 29  august_min_temp            75757 non-null  int64
 30  august_avg_temp            75757 non-null  float64
 31  august_max_temp            75757 non-null  int64
 32  september_min_temp         75757 non-null  int64
 33  september_avg_temp         75757 non-null  float64
 34  september_max_temp         75757 non-null  int64
 35  october_min_temp           75757 non-null  int64
 36  october_avg_temp           75757 non-null  float64
 37  october_max_temp           75757 non-null  int64
 38  november_min_temp          75757 non-null  int64
 39  november_avg_temp          75757 non-null  float64
 40  november_max_temp          75757 non-null  int64
 41  december_min_temp          75757 non-null  int64
 42  december_avg_temp          75757 non-null  float64
 43  december_max_temp          75757 non-null  int64
 44  cooling_degree_days        75757 non-null  int64
 45  heating_degree_days        75757 non-null  int64
 46  precipitation_inches       75757 non-null  float64
 47  snowfall_inches            75757 non-null  float64
 48  snowdepth_inches           75757 non-null  int64
 49  avg_temp                   75757 non-null  float64
 50  days_below_30F             75757 non-null  int64
 51  days_below_20F             75757 non-null  int64
 52  days_below_10F             75757 non-null  int64
 53  days_below_0F              75757 non-null  int64
 54  days_above_80F             75757 non-null  int64
 55  days_above_90F             75757 non-null  int64
 56  days_above_100F            75757 non-null  int64
 57  days_above_110F            75757 non-null  int64
 58  direction_max_wind_speed   34675 non-null  float64
 59  direction_peak_wind_speed  33946 non-null  float64
 60  max_wind_speed             34675 non-null  float64
 61  days_with_fog              29961 non-null  float64
 62  site_eui                   75757 non-null  float64
 63  id                         75757 non-null  int64
dtypes: float64(24), int64(37), object(3)
memory usage: 37.0+ MB

In [7]:
numeric_features_eda = [
    "floor_area",
    "year_built",
    "energy_star_rating",
    "ELEVATION",
    "january_min_temp",
    "january_avg_temp",
    "january_max_temp",
    "february_min_temp",
    "february_avg_temp",
    "february_max_temp",
    "march_min_temp",
    "march_avg_temp",
    "march_max_temp",
    "april_min_temp",
    "april_avg_temp",
    "april_max_temp",
    "may_min_temp",
    "may_avg_temp",
    "may_max_temp",
    "june_min_temp",
    "june_avg_temp",
    "june_max_temp",
    "july_min_temp",
    "july_avg_temp",
    "july_max_temp",
    "august_min_temp",
    "august_avg_temp",
    "august_max_temp",
    "september_min_temp",
    "september_avg_temp",
    "september_max_temp",
    "october_min_temp",
    "october_avg_temp",
    "october_max_temp",
    "november_min_temp",
    "november_avg_temp",
    "november_max_temp",
    "december_min_temp",
    "december_avg_temp",
    "december_max_temp",
    "cooling_degree_days",
    "heating_degree_days",
    "precipitation_inches",
    "snowfall_inches",
    "snowdepth_inches",
    "avg_temp",
    "days_below_30F",
    "days_below_20F",
    "days_below_10F",
    "days_below_0F",
    "days_above_80F",
    "days_above_90F",
    "days_above_100F",
    "days_above_110F",
    "max_wind_speed",
    "days_with_fog",
    "site_eui"
]

categorical_features_eda = [
    "Year_Factor",
    "State_Factor",
    "building_class",
    "facility_type",
    "direction_max_wind_speed",
    "direction_peak_wind_speed",
    "site_eui"
]

drop_columns = [
    "id"
]

In [ ]:
df.describe(include='all')

In [ ]:
pd.DataFrame(df[categorical_features_eda].drop(columns=["site_eui"]).nunique())

In [ ]:
pd.DataFrame(df[categorical_features_eda].drop(columns=["site_eui"]).isna().sum())

In [ ]:
pd.DataFrame(df[numeric_features_eda].drop(columns=["site_eui"]).isna().sum())

In [ ]:
chart_cat = alt.Chart(df.drop(columns="site_eui")).mark_bar().encode(
    x= alt.X(alt.repeat(), type='nominal'),
    y=alt.Y('count()')
).properties(
    width=600,
    height=200
).repeat(categorical_features_eda, columns=1, title = "Distribution of Categorical features"
)

chart_cat

In [ ]:
NG = alt.Chart(df, title="Site Energy units vs Year").mark_boxplot().encode(
    x='Year_Factor',
    y='site_eui',   
).properties(
    width=600,
    height=300
)

RT = alt.Chart(df, title="Site Energy Units per Facility Type").mark_boxplot().encode(
    x='facility_type',
    y='site_eui',   
).properties(
    width=800,
    height=300
)

LM = alt.Chart(df, title="Direction Peak Wind Speed vs Site Energy Units").mark_boxplot().encode(
    x='direction_peak_wind_speed',
    y='site_eui',   
).properties(
    width=600,
    height=300
)

WM = alt.Chart(df, title="Direction Max Wind Speed vs Site Energy Units").mark_boxplot().encode(
    x='direction_max_wind_speed',
    y='site_eui',   
).properties(
    width=600,
    height=250
)

chart = alt.vconcat(NG, RT, LM, WM)
chart

In [ ]:
# Numerical features
alt.Chart(df).mark_bar().encode(
    x=alt.X(alt.repeat(), type='quantitative',bin=alt.Bin(maxbins=10)),
    y=alt.Y('count()')
).properties(
    width=200,
    height=100
).repeat(numeric_features_eda, columns=3, title="Distribution of Numerical Features" )

In [ ]:
num_rel_plot = alt.Chart(df).mark_circle().encode(
    alt.X(alt.repeat(), type='quantitative'),
    y=alt.Y("site_eui", type='quantitative')
).properties(
    width=200,
    height=200
).repeat(numeric_features_eda, columns = 3, title = "Site Energy Units vs Numerical features"
        )
num_rel_plot

In [ ]:
eui_over_years = alt.Chart(df.dropna(subset=["year_built"]), title = "Trend over years ").mark_area().encode(
                        x = "year_built:T",
                        y = "site_eui")
eui_over_years

In [ ]:
corr_df = (
    df.drop(["id"], axis = 1)
    .corr('spearman')
    .abs()
    .stack()
    .reset_index(name='corr'))


corr_matrix = alt.Chart(corr_df).mark_rect().encode(
    x='level_0',
    y='level_1',
    size='corr',
    color='corr')

corr_matrix